[tool.poetry]
name = "crosslingual-coreference"
version = "0.1.0"
description = "A multi-lingual approach to AllenNLP CoReference Resolution, along with a wrapper for spaCy."
authors = ["David Berenstein <david.berenstein@pandoraintelligence.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.7.1,<4.0"
allennlp = "^2.9.2"
spacy = "^3.2.3"
allennlp-models = "^2.9.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
